### ISSUE TITLE
static vs dynamic analysis?

### ISSUE THREAD

**Issue by giuliohome** [royans/domainrisk#1]
Shouldn't it be a **recursive analysis**, as each loaded script might load further scripts?

Other suggestions
- parametric bash command: `MYDOMAIN=google.com bash -c 'python domainrisk.py $MYDOMAIN | tee $MYDOMAIN.txt | wc -l'`
- producing a `pip freeze > requirements.txt`

**Comment by royans** [comment]
Thanks for the great feedback.
- I've added a batch script to make this simpler
- It leaves a file per domain in /tmp/ if someone wants to inspect it as well
-  And added requirements.txt

**Comment by royans** [comment]
Closing.

**Comment by giuliohome** [comment]
Thank you very much for your support! And for sharing this repository in the first place!
